# 本文件一个代表一个录制任务，这里的设置基本上包含了所有可用的参数
# 配置文件编写请参考 https://github.com/SmallPeaches/DanmakuRender 

# 直播间链接
url: 'https://www.douyu.com/290935'

# 录制输出文件夹，设置为空则使用主播名称作为文件夹
output_dir: ./直播回放

# 录制文件名称格式，可使用关键字替换，默认效果：飞天狙想要努力变胖-2023年3月1日20点30分，注意这里不能含有冒号，斜杠等非法字符！！
output_name: '{STREAMER}-{YEAR}年{MONTH}月{DAY}日{HOUR}点{MINUTE}分'

# 录制程序引擎，可选ffmpeg（由ffmpeg提供拉流服务）或者streamgears（使用streamgears提供拉流服务，此功能正在测试）
# 在使用streamgears作为录制引擎时，录制视频格式只能是flv
engine: ffmpeg

# 录播分段时间（秒），默认一个小时
segment: 3600

# 是否录制弹幕
danmaku: True

# 是否录制直播流
video: True

# 启动自动渲染
auto_render: False

# 延迟下播计时（分钟）
# 使用这个功能可以把主播短暂下播又开播认定为同一场直播
end_cnt: 5

# 录制分辨率，此功能暂不可用
resolution: ~

# 录制视频的格式，默认flv
# 使用streamgears作为录制引擎应该使用flv
vid_format: flv

# 直播流CDN选项
# 对于虎牙直播，此项可选al, tx, hw等cdn服务器的缩写，默认tx
# 对于B站，此项可选0-n表示不同的cdn服务器，默认为0，也可以输入特定的CDN域名前缀，例如 c1--cn-gotcha208
# 斗鱼和抖音暂时没用
flow_cdn: ~

# 高级视频录制参数，具体可用选项请参考文档
advanced_video_args:
  # 开播检测间隔，每隔这样一段时间检测一次是否开播
  start_check_interval: 10

# 以下是弹幕录制参数

# 弹幕录制格式，只能选择ass
dm_format: ass 

# 弹幕上下间距（行距），设置为0-1的表示为视频宽度的倍数，设置为大于1的数表示像素，默认6
margin_h: 6

# 弹幕左右间距，设置为-1表示允许弹幕叠加，设置为0-1的表示间距为视频宽度的倍数，设置为大于1的数表示像素，默认0.05
# 实际上这个东西就是弹幕密度，弹幕左右间距越大密度越小
margin_w: 0.05

# 指定弹幕占屏幕的最大比例（即屏幕上半部分有多少可以用来显示弹幕），默认为0.4
dmrate: 0.4

# 指定弹幕字体，默认为微软雅黑字体(Microsoft YaHei)
font: Microsoft YaHei

# 指定弹幕字体大小，默认为36
fontsize: 36

# Distance from Screen Top 弹幕距离屏幕顶端的距离（像素，例如20，表示距离屏幕顶端20px）
dst: 20

# 指定单条弹幕持续时间（秒），默认为16
dmduration: 16

# 指定弹幕不透明度，默认为0.8
opacity: 0.8

# 使用自适应弹幕大小（会让把设置的弹幕大小按1080P标准缩放）
auto_fontsize: True

# 弹幕描边颜色(6位十六进制)
outlinecolor: 000000

# 弹幕描边宽度
outlinesize: 1.0

# 弹幕过滤规则，一个正则表达式数组（也可以直接输入关键字），满足其中任意条件的弹幕将被过滤，默认为空（不过滤弹幕）
# 例如：[菜, fw]
dm_filter: []

# 高级弹幕录制参数，具体可用选项请参考文档
advanced_dm_args: ~

# 上传参数，如果不需要上传就把下面的都删了

# 自动清理
clean:
  # 清理方法，可选copy（复制），move（移动），delete（删除），默认不清理
  # 请注意：清理过程不可逆！最好还是自己手动清理！
  method: ~

  # 目标文件夹，文件夹不存在会自动创建，可以使用关键字替换
  dest: ~

  # 只处理上传完成的视频，此功能暂时只在启用实时上传时有效，默认true
  # 如果想在只上传弹幕视频时自动清理原视频，请设置为false
  # 特别提示：既上传原视频又设置为false可能会导致不可控的结果！
  strict: True

  # 清理延迟（秒），在上传完成后会过一段时间再清理，默认172800（48小时）
  delay: 172800
